### ISSUE TITLE
Hive tables are not automatically created

### ISSUE THREAD

**Issue by frbattid** [telefonicaid/fiware-connectors#323]
Several users are reporting that Hive tables are not automatically created by Cygnus:

http://stackoverflow.com/questions/28583944/cygnus-release-0-6-0-does-not-create-hive-extended-tables
http://stackoverflow.com/questions/27918545/automatic-creation-of-the-hive-tables-on-cosmos

Cygnus does not log an exception nor any error message, except for `Creating Hive external table...`.

**Comment by neich** [comment]
Hi,

I'm the author of the latest question at SO. I've remotely debugged my cygnus instance and I've found the error. It turns out to be an outdated libthrift version. Now version 0.7 is being used, and you need 0.9. With 0.7 there is a method not found error regarding `TProtocol.getSchema()` that does not exists in 0.7. And `HiveClient.java` at cygnus is not capturing the error because it is catching only `Exception` (`HiveClient.java:76`) and `getConnection()` (`HiveClient.java:69`) is throwing an `Error`.

I've updated the `pom.xml` file, and I have changed Exception for Throwable to catch exceptions and errors. I'll send a pull request with the changes.

**Comment by frbattid** [comment]
Hi neich,

First of all, thank you very much!

You are absolutely right, it is a problem with the libthrift library. The funny thing is that it was already fixed! :) I completly forgot that the README says:

<i>libthrift-0.9.1.jar must overwrite APACHE_FLUME_HOME/lib/libthrift-0.7.0.jar (it can be got from the following URL: http://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.9.1/libthrift-0.9.1.jar)</i>

Being said that, I think it is not enough by using the appropriate libthrift version from Cygnus because Flume will always prefer the version located under /path/to/apache-flume-1.4.0-bin/lib than the Cygnus one, even if you build with dependencies. Did your fix worked without replacing the Flume's library?

**Comment by neich** [comment]
Hi,

Yes, with that changes cygnus works ok and creates the Hive tables. I didn't need to overwrite the flume's version. But I didn't make extensive testing ...

Ok, now I've seen the comment in the README about the thrift library. I though that only applied when you were building without dependencies. Now I see that flume uses libthrift 0.7.

Feel free to fix it your way. Anyway, I think that is better to have the catch with Throwable instead of Exception to be able to capture all the problems.

**Comment by frbattid** [comment]
Hi,

The question is I tried by only editing the pom.xml, but it did not worked for me :( Flume always tried to use its own version of the library. Anyway. I won't discard your solution until I test it more widely (I'll add it as techdebt). In the meantime, I think we'll maintain the Flume's library replacement by encouraging the users to do it in a clearer/enphasized way. Even, we are thinking to "hide" the installation by sources and enforcing the installation from RPM, which automatically replaces libthrift.

I agree with the `Throwable` catch.

Thanks again!

**Comment by neich** [comment]
+1 for RPM  installation

**Comment by frbattid** [comment]
In addition, post your solution at stackoverflow.com, please, so I can vote and comment your solution.

**Comment by frbattid** [comment]
Fixed (not really fixed by some modification in the README to make it clearer) in PR https://github.com/telefonicaid/fiware-connectors/pull/325

**Comment by frbattid** [comment]
Added this techdebt issue https://github.com/telefonicaid/fiware-connectors/issues/326
